language: php

branches:
  except:
    - legacy
#  only:
#    - master

php:
  - 7.3
  - 7.4
  - 8.0

env:
  global:
    - LOG_DIR=build/logs
    - CODECOV_TOKEN=db7401ff-3226-4288-af9a-56386d63ae43

before_install:

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - composer clear
  - composer install --no-scripts -vvv
  - curl --data-binary @codecov.yml https://codecov.io/validate

jobs:
  include:
    - stage: Test
      script:
        - mkdir -p build/tests
        - XDEBUG_MODE=coverage phpunit --configuration phpunit.xml
      after_success:
        - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f build/tests/clover.xml